"""
Multi-backend GPU-accelerated Random Forest (CUDA, OpenCL, CPU, Hybrid).

Build with: maturin develop --features pyo3
"""

from typing import List, Optional, Tuple

class RandomForest:
    """Core random forest classifier/regressor with direct control over all parameters."""

    def __init__(self, seed: Optional[int] = None) -> None: ...

    def set_num_trees(self, n: int) -> None: ...
    def set_max_depth(self, d: int) -> None: ...
    def set_min_samples_leaf(self, m: int) -> None: ...
    def set_min_samples_split(self, m: int) -> None: ...
    def set_max_features(self, m: int) -> None: ...

    def set_task_type(self, task: str) -> None:
        """Set task type. Valid values: 'classification', 'class', 'regression', 'reg'."""
        ...

    def set_criterion(self, criterion: str) -> None:
        """Set split criterion. Valid values: 'gini', 'entropy', 'mse', 'variance', 'var'."""
        ...

    def set_random_seed(self, seed: int) -> None: ...

    def set_backend(self, backend: str) -> None:
        """Set compute backend. Valid values: 'cuda', 'opencl', 'cl', 'cpu', 'hybrid', 'mixed', 'auto'."""
        ...

    def load_data(self, data: List[float], targets: List[float], n_samples: int, n_features: int) -> None:
        """Load training data from flat lists (row-major)."""
        ...

    def load_csv(self, filename: str, target_column: int, has_header: bool) -> bool:
        """Load training data from a CSV file. Returns True on success."""
        ...

    def fit(self) -> None:
        """Train the forest on loaded data."""
        ...

    def predict(self, sample: List[float]) -> float:
        """Predict a single sample (regression value or majority-vote class as float)."""
        ...

    def predict_class(self, sample: List[float]) -> int:
        """Predict the class label for a single sample."""
        ...

    def predict_batch(self, samples: List[float], n_samples: int) -> List[float]:
        """Predict a batch of samples (flat row-major list)."""
        ...

    def predict_batch_gpu(self, samples: List[float], n_samples: int) -> List[float]:
        """Predict a batch using the GPU backend."""
        ...

    def predict_batch_gpu_weighted(self, samples: List[float], n_samples: int, weights: List[float]) -> List[float]:
        """Predict a batch using the GPU backend with per-tree weights."""
        ...

    def calculate_oob_error(self) -> float:
        """Calculate out-of-bag error estimate."""
        ...

    def get_feature_importance(self, feature_index: int) -> float:
        """Get permutation importance for a single feature."""
        ...

    def get_feature_importances(self) -> List[float]:
        """Get permutation importances for all features."""
        ...

    def print_feature_importances(self) -> None: ...
    def print_forest_info(self) -> None: ...

    def save_model(self, filename: str) -> bool:
        """Serialize the model to a binary file. Returns True on success."""
        ...

    def load_model(self, filename: str) -> bool:
        """Load a model from a binary file. Returns True on success."""
        ...

    def predict_csv(self, input_file: str, output_file: str, has_header: bool) -> bool:
        """Run predictions on a CSV and write results to an output CSV."""
        ...

    def add_new_tree(self) -> None:
        """Fit and append one additional tree."""
        ...

    def remove_tree_at(self, tree_id: int) -> None:
        """Remove a tree by index (shifts subsequent trees)."""
        ...

    def retrain_tree_at(self, tree_id: int) -> None:
        """Re-fit a tree at the given index with a fresh bootstrap sample."""
        ...

    def get_num_trees(self) -> int: ...
    def get_num_features(self) -> int: ...
    def get_num_samples(self) -> int: ...
    def get_max_depth(self) -> int: ...

    @staticmethod
    def accuracy(predictions: List[float], actual: List[float]) -> float: ...

    @staticmethod
    def precision(predictions: List[float], actual: List[float], positive_class: int) -> float: ...

    @staticmethod
    def recall(predictions: List[float], actual: List[float], positive_class: int) -> float: ...

    @staticmethod
    def f1_score(predictions: List[float], actual: List[float], positive_class: int) -> float: ...

    @staticmethod
    def mean_squared_error(predictions: List[float], actual: List[float]) -> float: ...

    @staticmethod
    def r_squared(predictions: List[float], actual: List[float]) -> float: ...

class RandomForestFacade:
    """High-level facade providing tree inspection, feature toggling, weighted aggregation, and OOB tracking."""

    def __init__(self) -> None: ...

    def init_forest(self) -> None: ...

    def set_backend(self, backend: str) -> None:
        """Set compute backend. Valid values: 'cuda', 'opencl', 'cl', 'cpu', 'hybrid', 'mixed', 'auto'."""
        ...

    def set_hyperparameter(self, param_name: str, value: int) -> None:
        """Set a hyperparameter. Valid names: 'n_estimators', 'max_depth', 'min_samples_leaf', 'min_samples_split', 'max_features'."""
        ...

    def set_task_type(self, task: str) -> None:
        """Set task type. Valid values: 'classification', 'class', 'regression', 'reg'."""
        ...

    def set_criterion(self, criterion: str) -> None:
        """Set split criterion. Valid values: 'gini', 'entropy', 'mse', 'variance', 'var'."""
        ...

    def print_hyperparameters(self) -> None: ...

    def load_csv(self, filename: str) -> bool:
        """Load training data from a CSV (last column is the target). Returns True on success."""
        ...

    def train(self) -> None:
        """Train the forest."""
        ...

    def predict(self, sample: List[float]) -> float: ...
    def predict_class(self, sample: List[float]) -> int: ...
    def predict_batch(self, samples: List[float], n_samples: int) -> List[float]: ...
    def predict_batch_gpu(self, samples: List[float], n_samples: int) -> List[float]: ...

    def inspect_tree(self, tree_id: int) -> Tuple[int, int, int, int]:
        """Inspect a tree. Returns (num_nodes, max_depth, num_leaves, num_features_used)."""
        ...

    def print_tree_info(self, tree_id: int) -> None: ...
    def print_tree_structure(self, tree_id: int) -> None: ...

    def add_tree(self) -> None: ...
    def remove_tree(self, tree_id: int) -> None: ...
    def replace_tree(self, tree_id: int) -> None: ...
    def retrain_tree(self, tree_id: int) -> None: ...
    def get_num_trees(self) -> int: ...

    def enable_feature(self, feature_index: int) -> None: ...
    def disable_feature(self, feature_index: int) -> None: ...
    def reset_features(self) -> None: ...
    def print_feature_usage(self) -> None: ...
    def print_feature_importances(self) -> None: ...

    def set_aggregation_method(self, method: str) -> None:
        """Set aggregation method. Valid values: 'majority', 'majority-vote', 'weighted', 'weighted-vote', 'mean', 'weighted-mean'."""
        ...

    def set_tree_weight(self, tree_id: int, weight: float) -> None: ...
    def get_tree_weight(self, tree_id: int) -> float: ...
    def reset_tree_weights(self) -> None: ...

    def track_sample(self, sample_index: int) -> Tuple[int, int]:
        """Track a training sample. Returns (trees_influenced, oob_trees)."""
        ...

    def print_sample_tracking(self, sample_index: int) -> None: ...
    def print_oob_summary(self) -> None: ...
    def get_global_oob_error(self) -> float: ...

    def highlight_misclassified(self, predictions: List[float], actual: List[float]) -> None: ...

    def save_model(self, filename: str) -> bool: ...
    def load_model(self, filename: str) -> bool: ...
    def print_forest_info(self) -> None: ...
